### PR TITLE
Ugly but useful fix to avoid a 503 status code at PE deconnection.

### PR DESCRIPTION
**Pull request by celine-m-s**
When a user uses PE connect and disconnects, and when the "referrer" field is higher than about 1700 characters, a 503 status code is sent and the redirection to the home page does not work.

This happens only in staging and in production, not in a dev environment.

As the referral field includes a token, it's often very long and bugs are common.

I tried many many things to change the referral but Flask has a hard head and always resets it to its original content. See [the issue I opened on the Flask repo](https://github.com/pallets/flask/issues/3310).

This fix is ugly but it works...

### CODE REVIEW

**Comment by jab** [comment]
Thank you for reporting this. Can you submit a pull request that adds a test as a minimal reproducible example of the bug? Feel free to include a fix in the PR as well if you can.

**Comment by celine-m-s** [comment]
So, someone from the Flask team answered my question but they don't really have a solution. They say it's coming from our Nginx configuration that sets a headers max size. But I tried to enlarge it setting `large_client_header_buffers` to 16k and it does nothing. 
So... I don't know how we can find a solution to this bug but using this ugly fix.
@vgrange if you have an idea... :)

**Comment by celine-m-s** [comment]
Oui, je suis en train de voir pour les relancer !
Merci @vgrange !

**Comment by celine-m-s** [comment]
[Fixer le (vieux) bug au logout PE Connect LBB](https://trello.com/c/VG3gtv1T/65-fixer-le-vieux-bug-au-logout-pe-connect-lbb)

**Pull request merged**
